blank_issues_enabled: false
contact_links:
  - name: Discussions
    url: https://github.com/mynameistito/WOL-Android/discussions
    about: Ask questions or share ideas in Discussions rather than opening an issue.
